import { useState } from 'react';
import axios from 'axios';

/**
 * Razorpay Payment Modal Component
 * 
 * SECURITY ARCHITECTURE:
 * 1. Only PUBLIC Key (VITE_RAZORPAY_KEY) is in frontend code
 * 2. Secret Key stays ONLY in backend .env file
 * 3. Frontend calls backend to create order (backend uses secret key)
 * 4. Frontend calls backend to verify payment (backend uses secret key)
 * 5. Razorpay SDK handles payment collection on frontend
 * 
 * FLOW:
 * User clicks Pay → initiate() → Backend creates Order → Razorpay Modal Opens
 * User completes payment → Razorpay returns signature → Frontend verifies on backend
 * Backend confirms payment with Secret Key → Payment is secure
 */

const RazorpayPaymentModal = ({
  studentName,
  studentId,
  amount,
  invoiceId,
  onSuccess,
  onFailure,
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Get PUBLIC Razorpay Key from Vite environment
  // This is safe to expose - it's public information
  const PUBLIC_KEY = import.meta.env.VITE_RAZORPAY_KEY;

  // Backend API base URL - construct it properly without duplication
  const API_BASE_URL = `${import.meta.env.VITE_API_URL || 'http://localhost:5000'}/api`;

  if (!PUBLIC_KEY) {
    return (
      <div className="error-message">
        Error: Razorpay public key not configured. Check VITE_RAZORPAY_KEY in .env
      </div>
    );
  }

  /**
   * Step 1: Call backend to create Razorpay Order
   * Backend creates order using Secret Key (secure)
   * Only public Order ID is returned
   */
  const createOrderOnBackend = async () => {
    try {
      setLoading(true);
      setError(null);

      const response = await axios.post(`${API_BASE_URL}/payments/razorpay/create-order`, {
        amount: parseFloat(amount),
        invoiceId,
        currency: 'INR',
      });

      if (!response.data.success) {
        throw new Error(response.data.message || 'Failed to create order');
      }

      return response.data.data;
    } catch (err) {
      const errorMsg = err.response?.data?.message || err.message;
      setError(errorMsg);
      throw new Error(errorMsg);
    } finally {
      setLoading(false);
    }
  };

  /**
   * Step 2: Verify payment signature on backend
   * Frontend sends payment details to backend
   * Backend uses Secret Key to verify signature (secure)
   */
  const verifyPaymentOnBackend = async (paymentData) => {
    try {
      const response = await axios.post(`${API_BASE_URL}/payments/razorpay/verify`, {
        razorpay_order_id: paymentData.orderId,
        razorpay_payment_id: paymentData.paymentId,
        razorpay_signature: paymentData.signature,
        invoiceId,
        amount: paymentData.amount,
      });

      if (!response.data.success) {
        throw new Error(response.data.message || 'Payment verification failed');
      }

      return response.data;
    } catch (err) {
      const errorMsg = err.response?.data?.message || err.message;
      setError(errorMsg);
      throw new Error(errorMsg);
    }
  };

  /**
   * Step 3: Handle payment success from Razorpay
   * Called when user completes payment in Razorpay modal
   */
  const handlePaymentSuccess = async (response) => {
    try {
      setLoading(true);

      // Razorpay returns:
      // - razorpay_order_id: Order ID
      // - razorpay_payment_id: Payment ID (generated by Razorpay)
      // - razorpay_signature: HMAC-SHA256(orderId|paymentId)

      // Verify payment on backend using Secret Key
      const verificationResponse = await verifyPaymentOnBackend({
        orderId: response.razorpay_order_id,
        paymentId: response.razorpay_payment_id,
        signature: response.razorpay_signature,
        amount,
      });

      setLoading(false);

      // Payment verified successfully
      if (onSuccess) {
        onSuccess({
          paymentId: response.razorpay_payment_id,
          orderId: response.razorpay_order_id,
          amount,
          studentId,
          verificationResponse,
        });
      }
    } catch (err) {
      setLoading(false);
      setError(err.message);
      if (onFailure) {
        onFailure(err);
      }
    }
  };

  /**
   * Step 4: Handle payment failure from Razorpay
   */
  const handlePaymentFailure = (error) => {
    setLoading(false);
    const errorMsg = error?.error?.description || error?.message || 'Payment failed';
    setError(errorMsg);

    if (onFailure) {
      onFailure(error);
    }
  };

  /**
   * Step 5: Initialize Razorpay Payment Modal
   * This is the main function called when user clicks "Pay"
   */
  const initiate = async () => {
    try {
      setError(null);

      // Step 1: Create order on backend
      const orderData = await createOrderOnBackend();

      // Step 2: Load Razorpay SDK
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.async = true;

      script.onload = () => {
        // Step 3: Initialize Razorpay Modal
        const razorpayOptions = {
          // Order details from backend
          key: PUBLIC_KEY, // PUBLIC Key - safe to expose
          order_id: orderData.orderId, // Order ID from backend
          amount: orderData.amount, // Amount in paise
          currency: orderData.currency, // INR

          // User information
          prefill: {
            name: studentName,
            email: `student_${studentId}@institution.edu`,
            contact: '9999999999', // Optional: pre-fill if available
          },

          // Payment methods
          method: {
            upi: true,
            card: false,
            wallet: false,
            netbanking: false,
          },

          // Callbacks
          handler: handlePaymentSuccess, // Called after user completes payment
          modal: {
            ondismiss: () => {
              setError('Payment cancelled by user');
              if (onFailure) {
                onFailure(new Error('Payment cancelled'));
              }
            },
          },
        };

        // Step 4: Open Razorpay Modal
        const paymentObject = new window.Razorpay(razorpayOptions);
        paymentObject.open();

        // Handle modal open errors
        paymentObject.on('payment.failed', handlePaymentFailure);
      };

      script.onerror = () => {
        setError('Failed to load Razorpay SDK');
      };

      document.body.appendChild(script);
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div className="razorpay-payment-container">
      <div className="payment-details">
        <h3>Payment Summary</h3>
        <div className="detail-row">
          <span>Student Name:</span>
          <strong>{studentName}</strong>
        </div>
        <div className="detail-row">
          <span>Student ID:</span>
          <strong>{studentId}</strong>
        </div>
        <div className="detail-row">
          <span>Amount to Pay:</span>
          <strong>₹{parseFloat(amount).toFixed(2)}</strong>
        </div>
        {invoiceId && (
          <div className="detail-row">
            <span>Invoice ID:</span>
            <strong>{invoiceId}</strong>
          </div>
        )}
      </div>

      {error && <div className="error-message">{error}</div>}

      <button
        onClick={initiate}
        disabled={loading}
        className="payment-button"
      >
        {loading ? 'Processing...' : `Pay ₹${parseFloat(amount).toFixed(2)}`}
      </button>

      <div className="payment-info">
        <p>
          <strong>Payment Method:</strong> UPI (Google Pay, PhonePe, PayTM, etc.)
        </p>
        <p>
          <strong>Amount will be:</strong> Deducted from your UPI-linked bank account
        </p>
        <p>
          <strong>Security:</strong> Your payment is secured by Razorpay. Your bank details
          are never shared with the institution.
        </p>
      </div>
    </div>
  );
};

export default RazorpayPaymentModal;
